from src.collect.google.get_places_from_google_api import get_google_places_for_current_of_higene_data_establishments
from src.collect.google.combine_to_overall_and_comments import combine_google_found_to_overall
from util import setup_logger

google_logger = setup_logger("google")
def get_and_combine_to_overall():
    for la in local_authorities:
        google_logger.debug("on city: {}".format(la))
        get_google_places_for_current_of_higene_data_establishments(la)
        combine_google_found_to_overall()

local_authorities= [
#"Southampton",
#"Corby",
#"Hinckley and Bosworth",
#"Rossendale",
#"Wiltshire",
#"Guildford",
#"Darlington",
#   "Barnsley",
#   "North Lincolnshire",
#"Hart",
	"Shropshire",
	"Chelmsford",
	"Horsham",
	"Islington",
	"Newport",
	"Craven",
	"Dartford",
	"Mid Devon",
	"Ipswich",
	"Tameside",
	"Epsom and Ewell",
	"Worthing",
	"Hackney",
	"Croydon",
	"Runnymede",
	"Rotherham",
	"Gloucester City",
	"Selby",
	"Stevenage",
	"York",
	"West Devon",
	"West Oxfordshire",
	"Trafford",
	"Shetland Islands",
	"North Somerset",
	"Fenland",
	"North Dorset",
	"Swansea",
	"Rochford",
	"Bridgend",
	"Tandridge",
	"Solihull",
	"Liverpool",
	"Hertsmere",
	"Lichfield",
	"Stratford-on-Avon",
	"Fife",
	"Bolton",
	"Allerdale",
	"Test Valley",
	"Tonbridge and Malling",
	"South Staffordshire",
	"Ashford",
	"North Devon",
	"Angus",
	"Carmarthenshire",
	"South Oxfordshire",
	"South Ayrshire",
	"East Renfrewshire",
	"Breckland",
	"Anglesey",
	"St Albans City",
	"South Cambridgeshire",
	"Lincoln City",
	"Nuneaton and Bedworth",
	"Rutland",
	"North Norfolk",
	"Cardiff",
	"Warwick",
	"Wyre",
	"Perth and Kinross",
	"Blackpool",
	"Waveney",
	"Hillingdon",
	"Castle Point",
	"West Berkshire",
	"Ceredigion",
	"Forest Heath",
	"Blaby",
	"Maldon",
	"Wandsworth",
	"Moray",
	"East Cambridgeshire",
	"Norwich City",
	"Barrow-in-Furness",
	"East Riding of Yorkshire",
	"South Northamptonshire",
	"East Hertfordshire",
	"Gateshead",
	"Merton",
	"Lewes",
	"Melton",
	"Broadland",
	"Preston",
	"Bury",
	"Bolsover",
	"Hounslow",
	"Reading",
	"Windsor and Maidenhead",
	"West Lothian",
	"Bradford",
	"Wychavon",
	"Carlisle City",
	"Christchurch",
	"Greenwich",
	"City of London Corporation",
	"Boston",
	"Rhondda Cynon Taf",
	"Wycombe",
	"Cherwell",
	"Oldham",
	"King's Lynn and West Norfolk",
	"Southwark",
	"Aylesbury Vale",
	"South Kesteven",
	"Midlothian",
	"Stoke-On-Trent",
	"Cannock Chase",
	"North East Lincolnshire",
	"Bromley",
	"Conwy",
	"Stockton On Tees",
	"Sefton",
	"Dumfries and Galloway",
	"Canterbury City",
	"Derry City and Strabane",
	"Bristol",
	"Huntingdonshire",
	"Worcester City",
	"Flintshire",
	"Bromsgrove",
	"Isle of Wight",
	"Winchester City",
	"Falkirk",
	"Doncaster",
	"Newham",
	"Swindon",
	"Weymouth and Portland",
	"Rother",
	"Watford",
	"Waltham Forest",
	"Bassetlaw",
	"Causeway Coast and Glens",
	"Clackmannanshire",
	"Braintree",
	"Newry, Mourne and Down",
	"South Lanarkshire",
	"Hambleton",
	"Kingston-Upon-Thames",
	"Orkney Islands",
	"Great Yarmouth",
	"Birmingham",
	"Gedling",
	"West Somerset",
	"Waverley",
	"Medway",
	"Argyll and Bute",
	"Elmbridge",
	"Harlow",
	"Stafford",
	"Sevenoaks",
	"Rugby",
	"Scottish Borders",
	"Broxtowe",
	"Suffolk Coastal",
	"Spelthorne",
	"Camden"

        ]

if __name__ == "__main__":
    get_and_combine_to_overall()