
def get_hygine_data_source():

    return {
    "Babergh": "http://ratings.food.gov.uk/OpenDataFiles/FHRS297en-GB.xml",
    "Basildon": "http://ratings.food.gov.uk/OpenDataFiles/FHRS109en-GB.xml",
    "Bedford": "http://ratings.food.gov.uk/OpenDataFiles/FHRS701en-GB.xml",
    "Braintree": "http://ratings.food.gov.uk/OpenDataFiles/FHRS110en-GB.xml",
    "Breckland": "http://ratings.food.gov.uk/OpenDataFiles/FHRS227en-GB.xml",
    "Brentwood": "http://ratings.food.gov.uk/OpenDataFiles/FHRS111en-GB.xml",
    "Broadland": "http://ratings.food.gov.uk/OpenDataFiles/FHRS228en-GB.xml",
    "Broxbourne": "http://ratings.food.gov.uk/OpenDataFiles/FHRS155en-GB.xml",
    "Cambridge City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS027en-GB.xml",
    "Castle Point": "http://ratings.food.gov.uk/OpenDataFiles/FHRS112en-GB.xml",
    "Central Bedfordshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS702en-GB.xml",
    "Chelmsford": "http://ratings.food.gov.uk/OpenDataFiles/FHRS113en-GB.xml",
    "Colchester": "http://ratings.food.gov.uk/OpenDataFiles/FHRS114en-GB.xml",
    "Dacorum": "http://ratings.food.gov.uk/OpenDataFiles/FHRS156en-GB.xml",
    "East Cambridgeshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS028en-GB.xml",
    "East Hertfordshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS157en-GB.xml",
    "Epping Forest": "http://ratings.food.gov.uk/OpenDataFiles/FHRS115en-GB.xml",
    "Fenland": "http://ratings.food.gov.uk/OpenDataFiles/FHRS029en-GB.xml",
    "Forest Heath": "http://ratings.food.gov.uk/OpenDataFiles/FHRS298en-GB.xml",
    "Great Yarmouth": "http://ratings.food.gov.uk/OpenDataFiles/FHRS229en-GB.xml",
    "Harlow": "http://ratings.food.gov.uk/OpenDataFiles/FHRS116en-GB.xml",
    "Hertsmere": "http://ratings.food.gov.uk/OpenDataFiles/FHRS158en-GB.xml",
    "Huntingdonshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS030en-GB.xml",
    "Ipswich": "http://ratings.food.gov.uk/OpenDataFiles/FHRS299en-GB.xml",
    "King's Lynn and West Norfolk": "http://ratings.food.gov.uk/OpenDataFiles/FHRS230en-GB.xml",
    "Luton": "http://ratings.food.gov.uk/OpenDataFiles/FHRS869en-GB.xml",
    "Maldon": "http://ratings.food.gov.uk/OpenDataFiles/FHRS117en-GB.xml",
    "Mid Suffolk": "http://ratings.food.gov.uk/OpenDataFiles/FHRS300en-GB.xml",
    "North Hertfordshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS159en-GB.xml",
    "North Norfolk": "http://ratings.food.gov.uk/OpenDataFiles/FHRS231en-GB.xml",
    "Norwich City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS232en-GB.xml",
    "Peterborough City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS888en-GB.xml",
    "Rochford": "http://ratings.food.gov.uk/OpenDataFiles/FHRS118en-GB.xml",
    "South Cambridgeshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS032en-GB.xml",
    "South Norfolk": "http://ratings.food.gov.uk/OpenDataFiles/FHRS233en-GB.xml",
    "Southend-On-Sea": "http://ratings.food.gov.uk/OpenDataFiles/FHRS893en-GB.xml",
    "St Albans City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS160en-GB.xml",
    "St Edmundsbury": "http://ratings.food.gov.uk/OpenDataFiles/FHRS301en-GB.xml",
    "Stevenage": "http://ratings.food.gov.uk/OpenDataFiles/FHRS161en-GB.xml",
    "Suffolk Coastal": "http://ratings.food.gov.uk/OpenDataFiles/FHRS302en-GB.xml",
    "Tendring": "http://ratings.food.gov.uk/OpenDataFiles/FHRS120en-GB.xml",
    "Three Rivers": "http://ratings.food.gov.uk/OpenDataFiles/FHRS162en-GB.xml",
    "Thurrock": "http://ratings.food.gov.uk/OpenDataFiles/FHRS894en-GB.xml",
    "Uttlesford": "http://ratings.food.gov.uk/OpenDataFiles/FHRS122en-GB.xml",
    "Watford": "http://ratings.food.gov.uk/OpenDataFiles/FHRS163en-GB.xml",
    "Waveney": "http://ratings.food.gov.uk/OpenDataFiles/FHRS303en-GB.xml",
    "Welwyn Hatfield": "http://ratings.food.gov.uk/OpenDataFiles/FHRS164en-GB.xml",
    "Amber Valley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS062en-GB.xml",
    "Ashfield": "http://ratings.food.gov.uk/OpenDataFiles/FHRS259en-GB.xml",
    "Bassetlaw": "http://ratings.food.gov.uk/OpenDataFiles/FHRS260en-GB.xml",
    "Blaby": "http://ratings.food.gov.uk/OpenDataFiles/FHRS209en-GB.xml",
    "Bolsover": "http://ratings.food.gov.uk/OpenDataFiles/FHRS063en-GB.xml",
    "Boston": "http://ratings.food.gov.uk/OpenDataFiles/FHRS219en-GB.xml",
    "Broxtowe": "http://ratings.food.gov.uk/OpenDataFiles/FHRS261en-GB.xml",
    "Charnwood": "http://ratings.food.gov.uk/OpenDataFiles/FHRS210en-GB.xml",
    "Chesterfield": "http://ratings.food.gov.uk/OpenDataFiles/FHRS064en-GB.xml",
    "Corby": "http://ratings.food.gov.uk/OpenDataFiles/FHRS235en-GB.xml",
    "Daventry": "http://ratings.food.gov.uk/OpenDataFiles/FHRS236en-GB.xml",
    "Derby City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS871en-GB.xml",
    "Derbyshire Dales": "http://ratings.food.gov.uk/OpenDataFiles/FHRS070en-GB.xml",
    "East Lindsey": "http://ratings.food.gov.uk/OpenDataFiles/FHRS220en-GB.xml",
    "East Northamptonshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS237en-GB.xml",
    "Erewash": "http://ratings.food.gov.uk/OpenDataFiles/FHRS066en-GB.xml",
    "Gedling": "http://ratings.food.gov.uk/OpenDataFiles/FHRS262en-GB.xml",
    "Harborough": "http://ratings.food.gov.uk/OpenDataFiles/FHRS211en-GB.xml",
    "High Peak": "http://ratings.food.gov.uk/OpenDataFiles/FHRS067en-GB.xml",
    "Hinckley and Bosworth": "http://ratings.food.gov.uk/OpenDataFiles/FHRS212en-GB.xml",
    "Kettering": "http://ratings.food.gov.uk/OpenDataFiles/FHRS238en-GB.xml",
    "Leicester City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS878en-GB.xml",
    "Lincoln City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS221en-GB.xml",
    "Mansfield": "http://ratings.food.gov.uk/OpenDataFiles/FHRS263en-GB.xml",
    "Melton": "http://ratings.food.gov.uk/OpenDataFiles/FHRS214en-GB.xml",
    "Newark and Sherwood": "http://ratings.food.gov.uk/OpenDataFiles/FHRS264en-GB.xml",
    "North East Derbyshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS068en-GB.xml",
    "North Kesteven": "http://ratings.food.gov.uk/OpenDataFiles/FHRS222en-GB.xml",
    "North West Leicestershire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS215en-GB.xml",
    "Northampton": "http://ratings.food.gov.uk/OpenDataFiles/FHRS239en-GB.xml",
    "Nottingham City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS899en-GB.xml",
    "Oadby and Wigston": "http://ratings.food.gov.uk/OpenDataFiles/FHRS216en-GB.xml",
    "Rushcliffe": "http://ratings.food.gov.uk/OpenDataFiles/FHRS266en-GB.xml",
    "Rutland": "http://ratings.food.gov.uk/OpenDataFiles/FHRS879en-GB.xml",
    "South Derbyshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS069en-GB.xml",
    "South Holland": "http://ratings.food.gov.uk/OpenDataFiles/FHRS223en-GB.xml",
    "South Kesteven": "http://ratings.food.gov.uk/OpenDataFiles/FHRS224en-GB.xml",
    "South Northamptonshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS240en-GB.xml",
    "Wellingborough": "http://ratings.food.gov.uk/OpenDataFiles/FHRS241en-GB.xml",
    "West Lindsey": "http://ratings.food.gov.uk/OpenDataFiles/FHRS225en-GB.xml",
    "Barking and Dagenham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS501en-GB.xml",
    "Barnet": "http://ratings.food.gov.uk/OpenDataFiles/FHRS502en-GB.xml",
    "Bexley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS503en-GB.xml",
    "Brent": "http://ratings.food.gov.uk/OpenDataFiles/FHRS504en-GB.xml",
    "Bromley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS505en-GB.xml",
    "Camden": "http://ratings.food.gov.uk/OpenDataFiles/FHRS506en-GB.xml",
    "City of London Corporation": "http://ratings.food.gov.uk/OpenDataFiles/FHRS508en-GB.xml",
    "Croydon": "http://ratings.food.gov.uk/OpenDataFiles/FHRS507en-GB.xml",
    "Ealing": "http://ratings.food.gov.uk/OpenDataFiles/FHRS509en-GB.xml",
    "Enfield": "http://ratings.food.gov.uk/OpenDataFiles/FHRS510en-GB.xml",
    "Greenwich": "http://ratings.food.gov.uk/OpenDataFiles/FHRS511en-GB.xml",
    "Hackney": "http://ratings.food.gov.uk/OpenDataFiles/FHRS512en-GB.xml",
    "Hammersmith and Fulham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS513en-GB.xml",
    "Haringey": "http://ratings.food.gov.uk/OpenDataFiles/FHRS514en-GB.xml",
    "Harrow": "http://ratings.food.gov.uk/OpenDataFiles/FHRS515en-GB.xml",
    "Havering": "http://ratings.food.gov.uk/OpenDataFiles/FHRS516en-GB.xml",
    "Hillingdon": "http://ratings.food.gov.uk/OpenDataFiles/FHRS517en-GB.xml",
    "Hounslow": "http://ratings.food.gov.uk/OpenDataFiles/FHRS518en-GB.xml",
    "Islington": "http://ratings.food.gov.uk/OpenDataFiles/FHRS519en-GB.xml",
    "Kensington and Chelsea": "http://ratings.food.gov.uk/OpenDataFiles/FHRS520en-GB.xml",
    "Kingston-Upon-Thames": "http://ratings.food.gov.uk/OpenDataFiles/FHRS521en-GB.xml",
    "Lambeth": "http://ratings.food.gov.uk/OpenDataFiles/FHRS522en-GB.xml",
    "Lewisham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS523en-GB.xml",
    "Merton": "http://ratings.food.gov.uk/OpenDataFiles/FHRS524en-GB.xml",
    "Newham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS525en-GB.xml",
    "Redbridge": "http://ratings.food.gov.uk/OpenDataFiles/FHRS526en-GB.xml",
    "Richmond-Upon-Thames": "http://ratings.food.gov.uk/OpenDataFiles/FHRS527en-GB.xml",
    "Southwark": "http://ratings.food.gov.uk/OpenDataFiles/FHRS528en-GB.xml",
    "Sutton": "http://ratings.food.gov.uk/OpenDataFiles/FHRS529en-GB.xml",
    "Tower Hamlets": "http://ratings.food.gov.uk/OpenDataFiles/FHRS530en-GB.xml",
    "Waltham Forest": "http://ratings.food.gov.uk/OpenDataFiles/FHRS531en-GB.xml",
    "Wandsworth": "http://ratings.food.gov.uk/OpenDataFiles/FHRS532en-GB.xml",
    "Westminster": "http://ratings.food.gov.uk/OpenDataFiles/FHRS533en-GB.xml",
    "Darlington": "http://ratings.food.gov.uk/OpenDataFiles/FHRS874en-GB.xml",
    "Durham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS706en-GB.xml",
    "Gateshead": "http://ratings.food.gov.uk/OpenDataFiles/FHRS410en-GB.xml",
    "Hartlepool": "http://ratings.food.gov.uk/OpenDataFiles/FHRS859en-GB.xml",
    "Middlesbrough": "http://ratings.food.gov.uk/OpenDataFiles/FHRS861en-GB.xml",
    "Newcastle Upon Tyne": "http://ratings.food.gov.uk/OpenDataFiles/FHRS416en-GB.xml",
    "North Tyneside": "http://ratings.food.gov.uk/OpenDataFiles/FHRS417en-GB.xml",
    "Northumberland": "http://ratings.food.gov.uk/OpenDataFiles/FHRS707en-GB.xml",
    "Redcar and Cleveland": "http://ratings.food.gov.uk/OpenDataFiles/FHRS860en-GB.xml",
    "River Tees": "http://ratings.food.gov.uk/OpenDataFiles/FHRS648en-GB.xml",
    "South Tyneside": "http://ratings.food.gov.uk/OpenDataFiles/FHRS427en-GB.xml",
    "Stockton On Tees": "http://ratings.food.gov.uk/OpenDataFiles/FHRS862en-GB.xml",
    "Sunderland": "http://ratings.food.gov.uk/OpenDataFiles/FHRS429en-GB.xml",
    "Allerdale": "http://ratings.food.gov.uk/OpenDataFiles/FHRS055en-GB.xml",
    "Barrow-in-Furness": "http://ratings.food.gov.uk/OpenDataFiles/FHRS056en-GB.xml",
    "Blackburn": "http://ratings.food.gov.uk/OpenDataFiles/FHRS897en-GB.xml",
    "Blackpool": "http://ratings.food.gov.uk/OpenDataFiles/FHRS898en-GB.xml",
    "Bolton": "http://ratings.food.gov.uk/OpenDataFiles/FHRS403en-GB.xml",
    "Burnley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS196en-GB.xml",
    "Bury": "http://ratings.food.gov.uk/OpenDataFiles/FHRS405en-GB.xml",
    "Carlisle City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS057en-GB.xml",
    "Cheshire East": "http://ratings.food.gov.uk/OpenDataFiles/FHRS703en-GB.xml",
    "Cheshire West and Chester": "http://ratings.food.gov.uk/OpenDataFiles/FHRS704en-GB.xml",
    "Chorley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS197en-GB.xml",
    "Copeland": "http://ratings.food.gov.uk/OpenDataFiles/FHRS058en-GB.xml",
    "Eden": "http://ratings.food.gov.uk/OpenDataFiles/FHRS059en-GB.xml",
    "Fylde": "http://ratings.food.gov.uk/OpenDataFiles/FHRS198en-GB.xml",
    "Halton": "http://ratings.food.gov.uk/OpenDataFiles/FHRS889en-GB.xml",
    "Hyndburn": "http://ratings.food.gov.uk/OpenDataFiles/FHRS199en-GB.xml",
    "Knowsley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS412en-GB.xml",
    "Lancaster City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS200en-GB.xml",
    "Liverpool": "http://ratings.food.gov.uk/OpenDataFiles/FHRS414en-GB.xml",
    "Manchester": "http://ratings.food.gov.uk/OpenDataFiles/FHRS415en-GB.xml",
    "Oldham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS418en-GB.xml",
    "Pendle": "http://ratings.food.gov.uk/OpenDataFiles/FHRS201en-GB.xml",
    "Preston": "http://ratings.food.gov.uk/OpenDataFiles/FHRS202en-GB.xml",
    "Ribble Valley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS203en-GB.xml",
    "Rochdale": "http://ratings.food.gov.uk/OpenDataFiles/FHRS419en-GB.xml",
    "Rossendale": "http://ratings.food.gov.uk/OpenDataFiles/FHRS204en-GB.xml",
    "Salford": "http://ratings.food.gov.uk/OpenDataFiles/FHRS422en-GB.xml",
    "Sefton": "http://ratings.food.gov.uk/OpenDataFiles/FHRS424en-GB.xml",
    "South Lakeland": "http://ratings.food.gov.uk/OpenDataFiles/FHRS060en-GB.xml",
    "South Ribble": "http://ratings.food.gov.uk/OpenDataFiles/FHRS205en-GB.xml",
    "St Helens": "http://ratings.food.gov.uk/OpenDataFiles/FHRS421en-GB.xml",
    "Stockport": "http://ratings.food.gov.uk/OpenDataFiles/FHRS428en-GB.xml",
    "Tameside": "http://ratings.food.gov.uk/OpenDataFiles/FHRS430en-GB.xml",
    "Trafford": "http://ratings.food.gov.uk/OpenDataFiles/FHRS431en-GB.xml",
    "Warrington": "http://ratings.food.gov.uk/OpenDataFiles/FHRS890en-GB.xml",
    "West Lancashire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS206en-GB.xml",
    "Wigan": "http://ratings.food.gov.uk/OpenDataFiles/FHRS434en-GB.xml",
    "Wirral": "http://ratings.food.gov.uk/OpenDataFiles/FHRS435en-GB.xml",
    "Wyre": "http://ratings.food.gov.uk/OpenDataFiles/FHRS207en-GB.xml",
    "Adur": "http://ratings.food.gov.uk/OpenDataFiles/FHRS323en-GB.xml",
    "Arun": "http://ratings.food.gov.uk/OpenDataFiles/FHRS324en-GB.xml",
    "Ashford": "http://ratings.food.gov.uk/OpenDataFiles/FHRS179en-GB.xml",
    "Aylesbury Vale": "http://ratings.food.gov.uk/OpenDataFiles/FHRS021en-GB.xml",
    "Basingstoke and Deane": "http://ratings.food.gov.uk/OpenDataFiles/FHRS131en-GB.xml",
    "Bracknell Forest": "http://ratings.food.gov.uk/OpenDataFiles/FHRS882en-GB.xml",
    "Brighton and Hove": "http://ratings.food.gov.uk/OpenDataFiles/FHRS875en-GB.xml",
    "Canterbury City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS180en-GB.xml",
    "Cherwell": "http://ratings.food.gov.uk/OpenDataFiles/FHRS268en-GB.xml",
    "Chichester": "http://ratings.food.gov.uk/OpenDataFiles/FHRS325en-GB.xml",
    "Chiltern": "http://ratings.food.gov.uk/OpenDataFiles/FHRS022en-GB.xml",
    "Crawley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS326en-GB.xml",
    "Dartford": "http://ratings.food.gov.uk/OpenDataFiles/FHRS181en-GB.xml",
    "Dover": "http://ratings.food.gov.uk/OpenDataFiles/FHRS182en-GB.xml",
    "East Hampshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS132en-GB.xml",
    "Eastbourne": "http://ratings.food.gov.uk/OpenDataFiles/FHRS102en-GB.xml",
    "Eastleigh": "http://ratings.food.gov.uk/OpenDataFiles/FHRS133en-GB.xml",
    "Elmbridge": "http://ratings.food.gov.uk/OpenDataFiles/FHRS305en-GB.xml",
    "Epsom and Ewell": "http://ratings.food.gov.uk/OpenDataFiles/FHRS306en-GB.xml",
    "Fareham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS134en-GB.xml",
    "Gosport": "http://ratings.food.gov.uk/OpenDataFiles/FHRS135en-GB.xml",
    "Gravesham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS184en-GB.xml",
    "Guildford": "http://ratings.food.gov.uk/OpenDataFiles/FHRS307en-GB.xml",
    "Hart": "http://ratings.food.gov.uk/OpenDataFiles/FHRS136en-GB.xml",
    "Hastings": "http://ratings.food.gov.uk/OpenDataFiles/FHRS103en-GB.xml",
    "Havant": "http://ratings.food.gov.uk/OpenDataFiles/FHRS137en-GB.xml",
    "Horsham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS327en-GB.xml",
    "Isle of Wight": "http://ratings.food.gov.uk/OpenDataFiles/FHRS867en-GB.xml",
    "Lewes": "http://ratings.food.gov.uk/OpenDataFiles/FHRS105en-GB.xml",
    "Maidstone": "http://ratings.food.gov.uk/OpenDataFiles/FHRS185en-GB.xml",
    "Medway": "http://ratings.food.gov.uk/OpenDataFiles/FHRS896en-GB.xml",
    "Mid Sussex": "http://ratings.food.gov.uk/OpenDataFiles/FHRS328en-GB.xml",
    "Milton Keynes": "http://ratings.food.gov.uk/OpenDataFiles/FHRS870en-GB.xml",
    "Mole Valley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS308en-GB.xml",
    "New Forest": "http://ratings.food.gov.uk/OpenDataFiles/FHRS138en-GB.xml",
    "Oxford City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS269en-GB.xml",
    "Portsmouth": "http://ratings.food.gov.uk/OpenDataFiles/FHRS876en-GB.xml",
    "Reading": "http://ratings.food.gov.uk/OpenDataFiles/FHRS884en-GB.xml",
    "Reigate and Banstead": "http://ratings.food.gov.uk/OpenDataFiles/FHRS309en-GB.xml",
    "Rother": "http://ratings.food.gov.uk/OpenDataFiles/FHRS106en-GB.xml",
    "Runnymede": "http://ratings.food.gov.uk/OpenDataFiles/FHRS310en-GB.xml",
    "Rushmoor": "http://ratings.food.gov.uk/OpenDataFiles/FHRS140en-GB.xml",
    "Sevenoaks": "http://ratings.food.gov.uk/OpenDataFiles/FHRS187en-GB.xml",
    "Shepway": "http://ratings.food.gov.uk/OpenDataFiles/FHRS188en-GB.xml",
    "Slough": "http://ratings.food.gov.uk/OpenDataFiles/FHRS885en-GB.xml",
    "South Buckinghamshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS024en-GB.xml",
    "South Oxfordshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS270en-GB.xml",
    "Southampton": "http://ratings.food.gov.uk/OpenDataFiles/FHRS877en-GB.xml",
    "Spelthorne": "http://ratings.food.gov.uk/OpenDataFiles/FHRS311en-GB.xml",
    "Surrey Heath": "http://ratings.food.gov.uk/OpenDataFiles/FHRS312en-GB.xml",
    "Swale": "http://ratings.food.gov.uk/OpenDataFiles/FHRS189en-GB.xml",
    "Tandridge": "http://ratings.food.gov.uk/OpenDataFiles/FHRS313en-GB.xml",
    "Test Valley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS142en-GB.xml",
    "Thanet": "http://ratings.food.gov.uk/OpenDataFiles/FHRS190en-GB.xml",
    "Tonbridge and Malling": "http://ratings.food.gov.uk/OpenDataFiles/FHRS191en-GB.xml",
    "Tunbridge Wells": "http://ratings.food.gov.uk/OpenDataFiles/FHRS192en-GB.xml",
    "Vale of White Horse": "http://ratings.food.gov.uk/OpenDataFiles/FHRS271en-GB.xml",
    "Waverley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS314en-GB.xml",
    "Wealden": "http://ratings.food.gov.uk/OpenDataFiles/FHRS107en-GB.xml",
    "West Berkshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS883en-GB.xml",
    "West Oxfordshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS272en-GB.xml",
    "Winchester City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS143en-GB.xml",
    "Windsor and Maidenhead": "http://ratings.food.gov.uk/OpenDataFiles/FHRS886en-GB.xml",
    "Woking": "http://ratings.food.gov.uk/OpenDataFiles/FHRS315en-GB.xml",
    "Wokingham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS887en-GB.xml",
    "Worthing": "http://ratings.food.gov.uk/OpenDataFiles/FHRS329en-GB.xml",
    "Wycombe": "http://ratings.food.gov.uk/OpenDataFiles/FHRS025en-GB.xml",
    "Bath and North East Somerset": "http://ratings.food.gov.uk/OpenDataFiles/FHRS857en-GB.xml",
    "Bournemouth": "http://ratings.food.gov.uk/OpenDataFiles/FHRS872en-GB.xml",
    "Bristol": "http://ratings.food.gov.uk/OpenDataFiles/FHRS855en-GB.xml",
    "Cheltenham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS124en-GB.xml",
    "Christchurch": "http://ratings.food.gov.uk/OpenDataFiles/FHRS084en-GB.xml",
    "Cornwall": "http://ratings.food.gov.uk/OpenDataFiles/FHRS705en-GB.xml",
    "Cotswold": "http://ratings.food.gov.uk/OpenDataFiles/FHRS125en-GB.xml",
    "East Devon": "http://ratings.food.gov.uk/OpenDataFiles/FHRS072en-GB.xml",
    "East Dorset": "http://ratings.food.gov.uk/OpenDataFiles/FHRS085en-GB.xml",
    "Exeter City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS073en-GB.xml",
    "Forest of Dean": "http://ratings.food.gov.uk/OpenDataFiles/FHRS126en-GB.xml",
    "Gloucester City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS127en-GB.xml",
    "Isles of Scilly": "http://ratings.food.gov.uk/OpenDataFiles/FHRS336en-GB.xml",
    "Mendip": "http://ratings.food.gov.uk/OpenDataFiles/FHRS281en-GB.xml",
    "Mid Devon": "http://ratings.food.gov.uk/OpenDataFiles/FHRS074en-GB.xml",
    "North Devon": "http://ratings.food.gov.uk/OpenDataFiles/FHRS075en-GB.xml",
    "North Dorset": "http://ratings.food.gov.uk/OpenDataFiles/FHRS086en-GB.xml",
    "North Somerset": "http://ratings.food.gov.uk/OpenDataFiles/FHRS858en-GB.xml",
    "Plymouth City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS891en-GB.xml",
    "Poole": "http://ratings.food.gov.uk/OpenDataFiles/FHRS873en-GB.xml",
    "Purbeck": "http://ratings.food.gov.uk/OpenDataFiles/FHRS088en-GB.xml",
    "Sedgemoor": "http://ratings.food.gov.uk/OpenDataFiles/FHRS282en-GB.xml",
    "South Gloucestershire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS856en-GB.xml",
    "South Hams": "http://ratings.food.gov.uk/OpenDataFiles/FHRS077en-GB.xml",
    "South Somerset": "http://ratings.food.gov.uk/OpenDataFiles/FHRS283en-GB.xml",
    "Stroud": "http://ratings.food.gov.uk/OpenDataFiles/FHRS128en-GB.xml",
    "Swindon": "http://ratings.food.gov.uk/OpenDataFiles/FHRS881en-GB.xml",
    "Taunton Deane": "http://ratings.food.gov.uk/OpenDataFiles/FHRS284en-GB.xml",
    "Teignbridge": "http://ratings.food.gov.uk/OpenDataFiles/FHRS078en-GB.xml",
    "Tewkesbury": "http://ratings.food.gov.uk/OpenDataFiles/FHRS129en-GB.xml",
    "Torbay": "http://ratings.food.gov.uk/OpenDataFiles/FHRS892en-GB.xml",
    "Torridge": "http://ratings.food.gov.uk/OpenDataFiles/FHRS080en-GB.xml",
    "West Devon": "http://ratings.food.gov.uk/OpenDataFiles/FHRS081en-GB.xml",
    "West Dorset": "http://ratings.food.gov.uk/OpenDataFiles/FHRS089en-GB.xml",
    "West Somerset": "http://ratings.food.gov.uk/OpenDataFiles/FHRS285en-GB.xml",
    "Weymouth and Portland": "http://ratings.food.gov.uk/OpenDataFiles/FHRS090en-GB.xml",
    "Wiltshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS709en-GB.xml",
    "Birmingham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS402en-GB.xml",
    "Bromsgrove": "http://ratings.food.gov.uk/OpenDataFiles/FHRS145en-GB.xml",
    "Cannock Chase": "http://ratings.food.gov.uk/OpenDataFiles/FHRS287en-GB.xml",
    "Coventry": "http://ratings.food.gov.uk/OpenDataFiles/FHRS407en-GB.xml",
    "Dudley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS409en-GB.xml",
    "East Staffordshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS288en-GB.xml",
    "Herefordshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS895en-GB.xml",
    "Lichfield": "http://ratings.food.gov.uk/OpenDataFiles/FHRS289en-GB.xml",
    "Malvern Hills": "http://ratings.food.gov.uk/OpenDataFiles/FHRS148en-GB.xml",
    "Newcastle-Under-Lyme": "http://ratings.food.gov.uk/OpenDataFiles/FHRS290en-GB.xml",
    "North Warwickshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS317en-GB.xml",
    "Nuneaton and Bedworth": "http://ratings.food.gov.uk/OpenDataFiles/FHRS318en-GB.xml",
    "Redditch": "http://ratings.food.gov.uk/OpenDataFiles/FHRS149en-GB.xml",
    "Rugby": "http://ratings.food.gov.uk/OpenDataFiles/FHRS319en-GB.xml",
    "Sandwell": "http://ratings.food.gov.uk/OpenDataFiles/FHRS423en-GB.xml",
    "Shropshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS708en-GB.xml",
    "Solihull": "http://ratings.food.gov.uk/OpenDataFiles/FHRS426en-GB.xml",
    "South Staffordshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS291en-GB.xml",
    "Stafford": "http://ratings.food.gov.uk/OpenDataFiles/FHRS292en-GB.xml",
    "Staffordshire Moorlands": "http://ratings.food.gov.uk/OpenDataFiles/FHRS293en-GB.xml",
    "Stoke-On-Trent": "http://ratings.food.gov.uk/OpenDataFiles/FHRS880en-GB.xml",
    "Stratford-on-Avon": "http://ratings.food.gov.uk/OpenDataFiles/FHRS320en-GB.xml",
    "Tamworth": "http://ratings.food.gov.uk/OpenDataFiles/FHRS295en-GB.xml",
    "Telford and Wrekin Council": "http://ratings.food.gov.uk/OpenDataFiles/FHRS900en-GB.xml",
    "Walsall": "http://ratings.food.gov.uk/OpenDataFiles/FHRS433en-GB.xml",
    "Warwick": "http://ratings.food.gov.uk/OpenDataFiles/FHRS321en-GB.xml",
    "Wolverhampton": "http://ratings.food.gov.uk/OpenDataFiles/FHRS436en-GB.xml",
    "Worcester City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS151en-GB.xml",
    "Wychavon": "http://ratings.food.gov.uk/OpenDataFiles/FHRS152en-GB.xml",
    "Wyre Forest": "http://ratings.food.gov.uk/OpenDataFiles/FHRS153en-GB.xml",
    "Barnsley": "http://ratings.food.gov.uk/OpenDataFiles/FHRS401en-GB.xml",
    "Bradford": "http://ratings.food.gov.uk/OpenDataFiles/FHRS404en-GB.xml",
    "Calderdale": "http://ratings.food.gov.uk/OpenDataFiles/FHRS406en-GB.xml",
    "Craven": "http://ratings.food.gov.uk/OpenDataFiles/FHRS250en-GB.xml",
    "Doncaster": "http://ratings.food.gov.uk/OpenDataFiles/FHRS408en-GB.xml",
    "East Riding of Yorkshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS863en-GB.xml",
    "Hambleton": "http://ratings.food.gov.uk/OpenDataFiles/FHRS251en-GB.xml",
    "Harrogate": "http://ratings.food.gov.uk/OpenDataFiles/FHRS252en-GB.xml",
    "Hull City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS866en-GB.xml",
    "Kirklees": "http://ratings.food.gov.uk/OpenDataFiles/FHRS411en-GB.xml",
    "Leeds": "http://ratings.food.gov.uk/OpenDataFiles/FHRS413en-GB.xml",
    "North East Lincolnshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS865en-GB.xml",
    "North Lincolnshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS864en-GB.xml",
    "Richmondshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS253en-GB.xml",
    "Rotherham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS420en-GB.xml",
    "Ryedale": "http://ratings.food.gov.uk/OpenDataFiles/FHRS254en-GB.xml",
    "Scarborough": "http://ratings.food.gov.uk/OpenDataFiles/FHRS255en-GB.xml",
    "Selby": "http://ratings.food.gov.uk/OpenDataFiles/FHRS256en-GB.xml",
    "Sheffield": "http://ratings.food.gov.uk/OpenDataFiles/FHRS425en-GB.xml",
    "Wakefield": "http://ratings.food.gov.uk/OpenDataFiles/FHRS432en-GB.xml",
    "York": "http://ratings.food.gov.uk/OpenDataFiles/FHRS868en-GB.xml",
    "Antrim and Newtownabbey": "http://ratings.food.gov.uk/OpenDataFiles/FHRS801en-GB.xml",
    "Ards and North Down": "http://ratings.food.gov.uk/OpenDataFiles/FHRS802en-GB.xml",
    "Armagh City, Banbridge and Craigavon": "http://ratings.food.gov.uk/OpenDataFiles/FHRS803en-GB.xml",
    "Belfast City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS807en-GB.xml",
    "Causeway Coast and Glens": "http://ratings.food.gov.uk/OpenDataFiles/FHRS805en-GB.xml",
    "Derry City and Strabane": "http://ratings.food.gov.uk/OpenDataFiles/FHRS813en-GB.xml",
    "Fermanagh and Omagh": "http://ratings.food.gov.uk/OpenDataFiles/FHRS816en-GB.xml",
    "Lisburn and Castlereagh City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS809en-GB.xml",
    "Mid and East Antrim": "http://ratings.food.gov.uk/OpenDataFiles/FHRS804en-GB.xml",
    "Mid Ulster": "http://ratings.food.gov.uk/OpenDataFiles/FHRS811en-GB.xml",
    "Newry, Mourne and Down": "http://ratings.food.gov.uk/OpenDataFiles/FHRS814en-GB.xml",
    "Aberdeen City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS760en-GB.xml",
    "Aberdeenshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS761en-GB.xml",
    "Angus": "http://ratings.food.gov.uk/OpenDataFiles/FHRS762en-GB.xml",
    "Argyll and Bute": "http://ratings.food.gov.uk/OpenDataFiles/FHRS763en-GB.xml",
    "Clackmannanshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS768en-GB.xml",
    "Comhairle nan Eilean Siar (Western Isles)": "http://ratings.food.gov.uk/OpenDataFiles/FHRS791en-GB.xml",
    "Dumfries and Galloway": "http://ratings.food.gov.uk/OpenDataFiles/FHRS770en-GB.xml",
    "Dundee City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS772en-GB.xml",
    "East Ayrshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS764en-GB.xml",
    "East Dunbartonshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS771en-GB.xml",
    "East Lothian": "http://ratings.food.gov.uk/OpenDataFiles/FHRS781en-GB.xml",
    "East Renfrewshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS787en-GB.xml",
    "Edinburgh (City of)": "http://ratings.food.gov.uk/OpenDataFiles/FHRS773en-GB.xml",
    "Falkirk": "http://ratings.food.gov.uk/OpenDataFiles/FHRS774en-GB.xml",
    "Fife": "http://ratings.food.gov.uk/OpenDataFiles/FHRS775en-GB.xml",
    "Glasgow City": "http://ratings.food.gov.uk/OpenDataFiles/FHRS776en-GB.xml",
    "Highland": "http://ratings.food.gov.uk/OpenDataFiles/FHRS777en-GB.xml",
    "Inverclyde": "http://ratings.food.gov.uk/OpenDataFiles/FHRS778en-GB.xml",
    "Midlothian": "http://ratings.food.gov.uk/OpenDataFiles/FHRS783en-GB.xml",
    "Moray": "http://ratings.food.gov.uk/OpenDataFiles/FHRS784en-GB.xml",
    "North Ayrshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS765en-GB.xml",
    "North Lanarkshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS779en-GB.xml",
    "Orkney Islands": "http://ratings.food.gov.uk/OpenDataFiles/FHRS785en-GB.xml",
    "Perth and Kinross": "http://ratings.food.gov.uk/OpenDataFiles/FHRS786en-GB.xml",
    "Renfrewshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS788en-GB.xml",
    "Scottish Borders": "http://ratings.food.gov.uk/OpenDataFiles/FHRS767en-GB.xml",
    "Shetland Islands": "http://ratings.food.gov.uk/OpenDataFiles/FHRS789en-GB.xml",
    "South Ayrshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS766en-GB.xml",
    "South Lanarkshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS780en-GB.xml",
    "Stirling": "http://ratings.food.gov.uk/OpenDataFiles/FHRS790en-GB.xml",
    "West Dunbartonshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS769en-GB.xml",
    "West Lothian": "http://ratings.food.gov.uk/OpenDataFiles/FHRS782en-GB.xml",
    "Anglesey": "http://ratings.food.gov.uk/OpenDataFiles/FHRS551en-GB.xml",
    "Blaenau Gwent": "http://ratings.food.gov.uk/OpenDataFiles/FHRS552en-GB.xml",
    "Bridgend": "http://ratings.food.gov.uk/OpenDataFiles/FHRS553en-GB.xml",
    "Caerphilly": "http://ratings.food.gov.uk/OpenDataFiles/FHRS555en-GB.xml",
    "Cardiff": "http://ratings.food.gov.uk/OpenDataFiles/FHRS556en-GB.xml",
    "Carmarthenshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS558en-GB.xml",
    "Ceredigion": "http://ratings.food.gov.uk/OpenDataFiles/FHRS557en-GB.xml",
    "Conwy": "http://ratings.food.gov.uk/OpenDataFiles/FHRS550en-GB.xml",
    "Denbighshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS559en-GB.xml",
    "Flintshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS560en-GB.xml",
    "Gwynedd": "http://ratings.food.gov.uk/OpenDataFiles/FHRS554en-GB.xml",
    "Merthyr Tydfil": "http://ratings.food.gov.uk/OpenDataFiles/FHRS561en-GB.xml",
    "Monmouthshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS562en-GB.xml",
    "Neath Port Talbot": "http://ratings.food.gov.uk/OpenDataFiles/FHRS563en-GB.xml",
    "Newport": "http://ratings.food.gov.uk/OpenDataFiles/FHRS564en-GB.xml",
    "Pembrokeshire": "http://ratings.food.gov.uk/OpenDataFiles/FHRS565en-GB.xml",
    "Powys": "http://ratings.food.gov.uk/OpenDataFiles/FHRS566en-GB.xml",
    "Rhondda Cynon Taf": "http://ratings.food.gov.uk/OpenDataFiles/FHRS567en-GB.xml",
    "Swansea": "http://ratings.food.gov.uk/OpenDataFiles/FHRS568en-GB.xml",
    "Torfaen": "http://ratings.food.gov.uk/OpenDataFiles/FHRS569en-GB.xml",
    "Vale of Glamorgan": "http://ratings.food.gov.uk/OpenDataFiles/FHRS570en-GB.xml",
    "Wrexham": "http://ratings.food.gov.uk/OpenDataFiles/FHRS571en-GB.xml"
}