export const COUNCILNAMES: string[] =
[
    "Harrow",
    "Malvern Hills",
    "Midlothian",
    "Fareham",
    "Melton",
    "Neath Port Talbot",
    "Fylde",
    "Crawley",
    "Redcar and Cleveland",
    "Warrington",
    "Redditch",
    "East Staffordshire",
    "Sefton",
    "Leeds",
    "Thanet",
    "Bradford",
    "North Dorset",
    "Central Bedfordshire",
    "Warwick",
    "Corby",
    "South Lanarkshire",
    "Kingston-Upon-Thames",
    "Havant",
    "Hounslow",
    "West Lancashire",
    "Rutland",
    "Mid Devon",
    "Mansfield",
    "Derry City and Strabane",
    "Hammersmith and Fulham",
    "Gwynedd",
    "South Northamptonshire",
    "High Peak",
    "Gedling",
    "Hart",
    "Ipswich",
    "Harrogate",
    "South Oxfordshire",
    "Southwark",
    "Dover",
    "Vale of White Horse",
    "Tandridge",
    "Tonbridge and Malling",
    "Dudley",
    "Dundee City",
    "West Berkshire",
    "Ashfield",
    "Trafford",
    "Elmbridge",
    "South Norfolk",
    "Maldon",
    "Amber Valley",
    "Test Valley",
    "Rochford",
    "Mid and East Antrim",
    "Cheltenham",
    "Clackmannanshire",
    "Haringey",
    "Oxford City",
    "Mid Sussex",
    "Barrow-in-Furness",
    "Enfield",
    "Shropshire",
    "Eastbourne",
    "Wyre",
    "Islington",
    "Perth and Kinross",
    "Mendip",
    "South Ayrshire",
    "Isle of Wight",
    "Salford",
    "Stoke-On-Trent",
    "Runnymede",
    "Lancaster City",
    "Fermanagh and Omagh",
    "Wyre Forest",
    "Torfaen",
    "Dumfries and Galloway",
    "York",
    "Lambeth",
    "Ashford",
    "Kirklees",
    "Herefordshire",
    "Leicester City",
    "Camden",
    "Torridge",
    "Hackney",
    "Dacorum",
    "Tower Hamlets",
    "Cornwall",
    "Craven",
    "Bristol",
    "Allerdale",
    "Antrim and Newtownabbey",
    "Harlow",
    "Teignbridge",
    "Coventry",
    "Fife",
    "Castle Point",
    "Preston",
    "Lisburn and Castlereagh City",
    "Moray",
    "Birmingham",
    "Vale of Glamorgan",
    "Knowsley",
    "Wellingborough",
    "South Gloucestershire",
    "Cardiff",
    "South Hams",
    "Redbridge",
    "Chichester",
    "Wandsworth",
    "Sunderland",
    "Cheshire West and Chester",
    "Derby City",
    "Oadby and Wigston",
    "East Hampshire",
    "South Kesteven",
    "Stevenage",
    "Blackpool",
    "Fenland",
    "Blaby",
    "Poole",
    "Chiltern",
    "East Lindsey",
    "Waveney",
    "Sevenoaks",
    "Swansea",
    "Hillingdon",
    "Falkirk",
    "Halton",
    "Liverpool",
    "Richmondshire",
    "Harborough",
    "King's Lynn and West Norfolk",
    "Wolverhampton",
    "Ribble Valley",
    "Hull City",
    "Tunbridge Wells",
    "Chelmsford",
    "South Somerset",
    "Staffordshire Moorlands",
    "Northumberland",
    "Woking",
    "Waverley",
    "Mole Valley",
    "Havering",
    "Medway",
    "Middlesbrough",
    "Arun",
    "Erewash",
    "Hastings",
    "North Tyneside",
    "South Holland",
    "Thurrock",
    "Rossendale",
    "East Ayrshire",
    "Hambleton",
    "Gravesham",
    "West Lothian",
    "Oldham",
    "Stockport",
    "Belfast City",
    "Flintshire",
    "North Lanarkshire",
    "Sedgemoor",
    "Wirral",
    "Brighton and Hove",
    "Doncaster",
    "Carmarthenshire",
    "East Devon",
    "Eastleigh",
    "Exeter City",
    "Swale",
    "St Albans City",
    "Maidstone",
    "East Dunbartonshire",
    "Carlisle City",
    "Newham",
    "Scottish Borders",
    "Newport",
    "Wigan",
    "Watford",
    "Boston",
    "Wrexham",
    "Manchester",
    "Portsmouth",
    "Ryedale",
    "Kettering",
    "Waltham Forest",
    "Telford and Wrekin Council",
    "Burnley",
    "Wycombe",
    "Sheffield",
    "Ceredigion",
    "South Staffordshire",
    "Derbyshire Dales",
    "South Ribble",
    "Plymouth City",
    "Suffolk Coastal",
    "Shetland Islands",
    "Basildon",
    "Cotswold",
    "Epping Forest",
    "North Hertfordshire",
    "Chorley",
    "Slough",
    "Peterborough City",
    "Great Yarmouth",
    "Isles of Scilly",
    "Norwich City",
    "Breckland",
    "Ealing",
    "Worcester City",
    "Gloucester City",
    "Wychavon",
    "Copeland",
    "Canterbury City",
    "Cherwell",
    "City of London Corporation",
    "Hartlepool",
    "Bromsgrove",
    "Newark and Sherwood",
    "Bolsover",
    "Gosport",
    "Westminster",
    "Horsham",
    "Conwy",
    "Stirling",
    "Bedford",
    "Dartford",
    "Aberdeen City",
    "Brentwood",
    "Bridgend",
    "Merthyr Tydfil",
    "Bolton",
    "Rochdale",
    "North Norfolk",
    "Milton Keynes",
    "Nottingham City",
    "North Ayrshire",
    "New Forest",
    "Southampton",
    "Forest Heath",
    "North Kesteven",
    "Scarborough",
    "Forest of Dean",
    "Pendle",
    "Glasgow City",
    "Merton",
    "East Hertfordshire",
    "Daventry",
    "Highland",
    "Barnet",
    "Armagh City, Banbridge and Craigavon",
    "Orkney Islands",
    "Shepway",
    "Spelthorne",
    "Lewisham",
    "Rhondda Cynon Taf",
    "Eden",
    "Hertsmere",
    "Broxtowe",
    "East Renfrewshire",
    "Tameside",
    "Blackburn",
    "Wakefield",
    "Aylesbury Vale",
    "Angus",
    "Pembrokeshire",
    "Charnwood",
    "Hinckley and Bosworth",
    "Lincoln City",
    "Kensington and Chelsea",
    "Causeway Coast and Glens",
    "South Derbyshire",
    "Argyll and Bute",
    "West Dorset",
    "Bassetlaw",
    "East Dorset",
    "Brent",
    "Croydon",
    "West Lindsey",
    "Torbay",
    "North Somerset",
    "Basingstoke and Deane",
    "Tendring",
    "Selby",
    "Caerphilly",
    "Northampton",
    "Blaenau Gwent",
    "Colchester",
    "Worthing",
    "Newry, Mourne and Down",
    "South Lakeland",
    "Surrey Heath",
    "River Tees",
    "Newcastle-Under-Lyme",
    "Babergh",
    "Walsall",
    "Guildford",
    "Uttlesford",
    "Monmouthshire",
    "South Cambridgeshire",
    "Epsom and Ewell",
    "Christchurch",
    "West Somerset",
    "Gateshead",
    "Wealden",
    "Richmond-Upon-Thames",
    "Huntingdonshire",
    "North Devon",
    "Broadland",
    "Bath and North East Somerset",
    "Stockton On Tees",
    "Adur",
    "Barking and Dagenham",
    "Stratford-on-Avon",
    "North Warwickshire",
    "Sutton",
    "North East Derbyshire",
    "Rother",
    "Inverclyde",
    "Nuneaton and Bedworth",
    "Rotherham",
    "Bracknell Forest",
    "Weymouth and Portland",
    "Sandwell",
    "Stroud",
    "Barnsley",
    "Welwyn Hatfield",
    "Powys",
    "Bexley",
    "West Oxfordshire",
    "Bournemouth",
    "Bromley",
    "Taunton Deane",
    "Reading",
    "Reigate and Banstead",
    "East Lothian",
    "Edinburgh (City of)",
    "Stafford",
    "East Northamptonshire",
    "Bury",
    "Purbeck",
    "Newcastle Upon Tyne",
    "Chesterfield",
    "Aberdeenshire",
    "Mid Ulster",
    "St Helens",
    "Mid Suffolk",
    "Tewkesbury",
    "Durham",
    "Solihull",
    "Denbighshire",
    "Lewes",
    "Darlington",
    "Luton",
    "Three Rivers",
    "North West Leicestershire",
    "South Tyneside",
    "Comhairle nan Eilean Siar (Western Isles)",
    "North East Lincolnshire",
    "Cambridge City",
    "Greenwich",
    "Ards and North Down",
    "South Buckinghamshire",
    "Windsor and Maidenhead",
    "Cheshire East",
    "Tamworth",
    "Wiltshire",
    "Wokingham",
    "Lichfield",
    "Braintree",
    "Rugby",
    "West Dunbartonshire",
    "St Edmundsbury",
    "East Riding of Yorkshire",
    "Renfrewshire",
    "Swindon",
    "Broxbourne",
    "West Devon",
    "Southend-On-Sea",
    "East Cambridgeshire",
    "North Lincolnshire",
    "Cannock Chase",
    "Rushcliffe",
    "Calderdale",
    "Rushmoor",
    "Winchester City",
    "Anglesey",
    "Hyndburn"
];

