export const CATGORIESLIST: string[] =
[

	"Chinese",
	"Bars",
	"French",
	"Cafes",
	"Coffee & Tea",
	"Sushi Bars",
	"Pubs",
	"Tapas Bars",
	"Thai",
	"Nightlife",
	"Mexican",
	"British",
	"Portuguese",
	"Italian",
	"Indian",
	"Fast Food",
	"Wine Bars",
	"Bakeries",
	"Malaysian",
	"Singaporean",
	"Restaurants",
	"Fish & Chips",
	"Hospitals",
	"Pakistani",
	"Greek",
	"Mediterranean",
	"Brazilian",
	"Spanish",
	"Polish",
	"Caribbean",
	"Turkish",
	"Japanese",
	"Butcher",
	"Irish",
	"Cheese Shops",
	"Sports Clubs",
	"Desserts",
	"Seafood",
	"Imported Food",
	"Caterers",
	"Asian Fusion",
	"Salad",
	"Hotels & Travel",
	"Halal",
	"Elementary Schools",
	"Gas & Service Stations",
	"Zoos",
	"Buffets",
	"Leisure Centers",
	"Cantonese",
	"Framing",
	"Himalayan/Nepalese",
	"Bangladeshi",
	"Pool Halls",
	"Sports Bars",
	"Child Care & Day Care",
	"Organic Stores",
	"Farms",
	"Festivals",
	"Soup",
	"Middle Schools & High Schools",
	"Adult Entertainment",
	"Swimming Pools",
	"Health & Medical",
	"Beauty & Spas",
	"Seafood Markets",
	"Religious Organizations",
	"Creperies",
	"Middle Eastern",
	"African",
	"Afghan",
	"Vietnamese",
	"Russian",
	"Korean",
	"Lebanese",
	"Chicken Shop",
	"Bubble Tea",
	"Books, Mags, Music & Video",
	"Juice Bars & Smoothies",
	"Basque",
	"Latin American",
	"Cuban",
	"Argentine",
	"Karaoke",
	"German",
	"Australian",
	"Counseling & Mental Health",
	"Tex-Mex",
	"Cooking Schools",
	"Austrian",
	"Ethiopian",
	"Hookah Bars",
	"Moroccan",
	"Bike Repair/Maintenance",
	"Bikes",
	"Specialty Food",
	"Milkshake Bars",
	"Cajun/Creole",
	"Noodles",
	"Scottish",
	"Dive Bars",
	"Georgian",
	"Bagels",
	"Hostels",
	"Local Flavor",
	"Peruvian",
	"Food Stands",
	"Day Spas",
	"Medical Spas",
	"Cafeteria",
	"Persian/Iranian",
	"Community Centers",
	"Adult Education",
	"Street Vendors",
	"Train Stations",
	"Scandinavian",
	"Gay Bars",
	"Donuts",
	"Dim Sum",
	"Taiwanese",
	"Wineries",
	"Ramen",
	"Comedy Clubs",
	"Stadiums & Arenas",
	"Casinos",
	"Bulgarian",
	"Sri Lankan",
	"Arabian",
	"Recreation Centers",
	"Herbs & Spices",
	"Bingo Halls",
	"Indonesian",
	"Beer Gardens",
	"Airport Lounges",
	"Food Trucks",
	"Southern",
	"Tiki Bars",
	"Airports",
	"Food Banks",
	"Irish Pub",
	"Kosher",
	"Distilleries",
	"Wine Tours",
	"Waffles",
	"Coffee & Tea Supplies",
	"Doctors",
	"Family Practice",
	"Falafel",
	"Armenian",
	"University Housing",
	"Pan Asian",
	"Szechuan",
	"Macarons",
	"Belgian",
	"Wholesale Stores",
	"Hawaiian",
	"Laser Tag",
	"Piano Bars",
	"Whiskey Bars",
	"Movers",
	"Golf Lessons",
	"Car Stereo Installation",
	"Pool & Billiards",
	"Cheesesteaks",
	"Pop-Up Restaurants",
	"Tutoring Centers",
	"Christmas Trees",
	"Insurance",
	"Car Wash",
	"Hospice",
	"Food Court",
	"Market Stalls",
	"Adult",
	"Cambodian",
	"Real Estate Services",
	"Cooking Classes",
	"Syrian",
	"Hungarian"
]


